- node/rpc/src/admin/api.rs
- node/rpc/src/admin/impl.rs
- node/rpc/src/config.rs
- node/rpc/src/lib.rs
- node/src/client/builder.rs
- node/src/config/convert.rs
- node/src/config/mod.rs
- node/sync/src/controllers/serial.rs
- node/sync/src/service.rs
- run/config.toml
- tests/test_framework/zgs_node.py
1. Add rpc `admin_terminateSync` to terminate file/chunks sync.
2. When p2p sync failed, do not allow to resync if goal changed.
3. Support to configure separate endpoint for admin and mine rpc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/15)
> Rpc enhancements

- node/miner/src/config.rs
- node/miner/src/mine.rs
- node/miner/src/pora.rs
- node/src/config/convert.rs
- node/src/config/mod.rs
- tests/long_time_mine_test_local.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/58)
> Configurable CPU usage on mine

- node/sync/src/auto_sync/batcher_random.rs
- node/sync/src/auto_sync/batcher_serial.rs
- node/sync/src/auto_sync/mod.rs
- node/sync/src/auto_sync/sync_store.rs
- node/sync/src/controllers/mod.rs
- node/sync/src/controllers/peers.rs
- node/sync/src/controllers/serial.rs
- node/sync/src/lib.rs
- node/sync/src/service.rs
- run/config.toml
1. Change default concurrent sync threads to avoid random sync rate limited.
2. Enhance log level in sync store.
3. Add `RwLock` in sync store to avoid concurrency issue.
4. Enhance `serial` sync log.
5. Wrap `Instant` for debug purpose.
6. Randomly pick a peer to sync chunks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/111)
> Fix some issues in sync package

- node/rpc/src/admin/api.rs
- node/rpc/src/admin/impl.rs
- node/sync/src/auto_sync/batcher.rs
- node/sync/src/auto_sync/batcher_serial.rs
Fix some auto sync issues:
1. Terminate file sync if failed. Otherwise, it will never be removed in memory automatically.
2. If file already finalized in db, then terminate the file sync immediately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/121)
> Terminate file sync if failed

- node/miner/src/mine.rs
pora info is important for storage mining, better to promote the logging level to info
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/192)
> change the Pora result from debug to info

- common/zgs_version/src/lib.rs
- node/Cargo.toml
- node/src/cli/mod.rs
1. Enhance `zgs_version` with tag info.
2. Use `zgs_version` for cli version info.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/211)
> Optimize zgs version

- tests/config/0gchain-init-genesis.sh
- tests/utility/build_binary.py
- use fixed 0g binary in integration test
`mine_with_market` test will fail randomly due to a precision bug in 0g chain. The bug will be fixed in https://github.com/0glabs/0g-chain/pull/74.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/218)
> test: use fixed 0g binary

- common/contract-interface/src/lib.rs
- node/log_entry_sync/src/sync_manager/mod.rs
- node/miner/src/miner_id.rs
- node/pruner/src/lib.rs
- node/router/src/libp2p_event_handler.rs
- node/src/client/builder.rs
- node/storage-async/src/lib.rs
- node/storage/benches/benchmark.rs
- node/storage/src/log_store/config.rs
- node/storage/src/log_store/flow_store.rs
- node/storage/src/log_store/log_manager.rs
- node/storage/src/log_store/mod.rs
- node/storage/src/log_store/tests.rs
- node/sync/src/auto_sync/sync_store.rs
- node/sync/src/auto_sync/tx_store.rs
- node/sync/src/controllers/serial.rs
- node/sync/src/service.rs
- node/sync/src/test_util.rs
This PR does the following:
1. separate flow db from data db so the snapshot can contain just the flow db without the data db
2. data db contains actually data, miner_id, shard_config, finalized indicator
3. flow db contains merkle, sync event statistics
4. pad tx after the sync period finished to allow for faster sync up.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/262)
> @peter/db split

- node/pruner/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/267)
> Wait for tx to be processed in pruner.

- node/storage/src/log_store/tx_store.rs
- node/sync/src/auto_sync/batcher.rs
- node/sync/src/auto_sync/batcher_random.rs
- node/sync/src/auto_sync/historical_tx_writer.rs
- node/sync/src/auto_sync/manager.rs
- node/sync/src/auto_sync/metrics.rs
- node/sync/src/auto_sync/mod.rs
- tests/sync_auto_random_v2_test.py
When node sync files only from neighbors, it will miss some `NewFile` gossip messages during downtime. As a result, these files will not be synced anymore.
Besides the current file sync based on neighbors notifications, launch another aysnc worker to sync all files, regardless of `NewFile` message received or not. If file unavailable on neighbor nodes, it will be timeout to find peers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/269)
> Supports to sync historical files without NewFile gossip message

- run/config-testnet-standard.toml
- run/config-testnet-turbo.toml
Increase default max number of sectors to 4x as before (~ 1000 GB).
User needs to adjust accordingly for more/less allowed storage capacity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/272)
> increase db_max_num_sectors to be about 1000GB

- node/rpc/src/zgs/impl.rs
- node/storage/src/log_store/log_manager.rs
- node/storage/src/log_store/mod.rs
- node/storage/src/log_store/tx_store.rs
- node/sync/src/auto_sync/batcher.rs
- node/sync/src/auto_sync/historical_tx_writer.rs
This index is used for upload/download segments and file status check.
In all the cases, if there is a finalized transaction, we should use it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/278)
> Return the first finalized tx by data root if possible. 

- README.md
- docs/onebox-test.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/283)
> Add new docs page for local testing

- README.md
- docs/onebox-test.md
**Typo Fixes:**
1. **"want build"** → **"want to build"**
2. **"run following"** → **"run the following"**
These changes fix grammatical errors in the documentation, improving readability and adherence to standard English.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/287)
> Fix grammatical typos in documentation 

- node/network/src/config.rs
- node/network/src/service.rs
- node/network/src/types/mod.rs
- node/network/src/types/topics.rs
- node/src/config/convert.rs
- node/src/config/mod.rs
- tests/sync_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/291)
> Optional subscribe FIND_CHUNKS topic

- node/network/src/types/mod.rs
- node/network/src/types/pubsub.rs
- node/network/src/types/topics.rs
- node/router/src/libp2p_event_handler.rs
- node/router/src/service.rs
- node/shared_types/src/lib.rs
- node/storage/src/config.rs
- node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/292)
> Refactor announce shard config pubsub message

- tests/test_framework/test_framework.py
Attempts to connect ZGS nodes should occur only after the node launches have been completed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/305)
> Fix node launch process in test framework

- docs/introduction.md
Hi team,  
I noticed a small typo in the phrase "to enable wide range of applications" where the article "a" was missing. This could potentially cause slight confusion or appear less polished in formal contexts.  
I've updated it to "to enable a wide range of applications" for correctness and to ensure clarity across all usages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/306)
> docs: typo fix Update introduction.md

- Cargo.lock
- node/Cargo.toml
- node/src/log.rs
It requires `tokio_unstable` in rust flags, so a `tokio-console` feature is added to be compatible with the default config. 
To compile with the tokio console enabled, compile with 
``RUSTFLAGS="--cfg tokio_unstable" cargo build --release --features tokio-console`` 
The usage of the tokio console can be found in https://github.com/tokio-rs/console.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/317)
> Add tokio console for debug.

- version-meld/discv5/src/kbucket.rs
- version-meld/eth2_ssz/src/decode/impls.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/313)
> chore: fix some comments

- version-meld/discv5/README.md
Hi,
I suggest two grammatical changes for this text:
First one: "it's" vs. "its":
"Each peer/node on the network is identified via it's ENR..." → "Each peer/node on the network is identified via its ENR..." Explanation: "It's" is a contraction of "it is," whereas "its" is the possessive form.
Second one: "PING/PONG's":
"through regular PING/PONG's with discovered nodes." → "through regular PING/PONGs with discovered nodes." Explanation: "PING/PONGs" should not have an apostrophe since it refers to a plural form, not possession.
Thanks and a happy new year.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/310)
> Typo fixed in: Update README.md

- common/lighthouse_metrics/src/lib.rs
- node/src/client/environment.rs
- Fixed "an varying" to "a varying" in `lib.rs`.
- Changed "a environment" to "an environment" in `environment.rs`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/314)
> Fix spelling errors

- scripts/check_abis.sh
I noticed that paths with spaces or special characters were causing issues in the script execution.
I've added quotes around `$(./scripts/search_abi.sh "$artifacts_path" "$contract_name.json")` to ensure proper handling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/318)
> fix: Fix path handling in script execution

- scripts/update_config.sh
I noticed that the `-in-place=''` option used in the sed command is incorrect.
The proper syntax for in-place editing with sed should be either `-i` or `-i''` (with an empty string after `-i` for compatibility with some sed versions).
This fix ensures the command works as expected across different environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/320)
> fix: Fix incorrect -in-place='' syntax Update update_config.sh

- node/network/src/behaviour/mod.rs
- node/network/tests/pm_tests.rs
- run/config-testnet-standard.toml
- run/config-testnet-turbo.toml
- run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/319)
> Fix code comments and bug report errors

- docs/architecture.md
- docs/incentive-mechanism/proof-of-random-access.md
- docs/k-v-store.md
- docs/transaction-processing.md
**Description:**
I was reading `docs/architecture.md` and noticed that the figure references (e.g., "Figure 1. The Architecture of 0G System") were present but no images were being displayed. The image paths were wrong. This PR makes all figure image references in the docs correct so that they will display. 
**Changes:**
Hard-coded image source URLs in:
- `docs/architecture.md`
- `docs/incentive-mechanism/proof-of-random-access.md`
- `docs/k-v-store.md`
- `docs/transaction-processing.md`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/335)
> docs: fix broken figure image paths across docs

- node/network/src/config.rs
- version-meld/enr/src/keys/mod.rs
- version-meld/enr/src/lib.rs
- Corrected spelling in `config.rs`:  
- `"recieved"` → `"received"`  
- Improved terminology in `mod.rs`:  
- `"useable"` → `"usable"`  
- Fixed wording in `lib.rs`:  
- `"differnet"` → `"different"`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/337)
> Fix spelling errors and correct minor errors

- node/file_location_cache/src/file_location_cache.rs
Сorrected multiple spelling errors in function names where "annoucement" was mistakenly used instead of "announcement." These changes improve code clarity, maintainability, and consistency in function naming.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/351)
>  Fix Typos in Function Names 

- scripts/update_abis.sh
I noticed an issue in the `copy_abis` function where the command `$(./scripts/search_abi.sh "$path/artifacts" "$contract_name.json")` was used without quotes. This could lead to problems if the returned path contains spaces or special characters. I've fixed this by wrapping the command substitution in double quotes, ensuring the path is handled correctly.
The updated line now looks like this:
```bash
copy_file "$(./scripts/search_abi.sh "$path/artifacts" "$contract_name.json")" "storage-contracts-abis/$contract_name.json"
``` 
This small change ensures the path is treated as a single argument, avoiding potential issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-n …
> Fixing bug with incorrect argument handling in copy_abis function

- tests/cli_submission_test.py
I noticed a typo in the code where the variable `entris` was being used. It should have been `entries`.
I’ve corrected this in all occurrences to ensure consistency and avoid any confusion.
The issue was particularly noticeable in the variable `num_of_entris`, which has now been updated to `num_of_entries`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/345)
> chore: Fixed error in variable name (entris to entries)

- common/append_merkle/src/proof.rs
I encountered an error in the last debugging session while initializing a new `Proof` using the `Proof::new` method. The error message simply was:
```rust
bail!("hash and path length mismatch");
```
This message did not include enough context to easily determine the problem. The error didn't state what lengths were being passed.
To improve this, I rewrote the error message to be more helpful. Now, if there is a mismatch, the error message will also indicate the actual lengths of the hash and the path. The new message is:
```rust
bail!("Proof::new: expected hash length = path.len() + 2, but got {} and {}", hash.len(), path.len());
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> improve error message in Proof::new to include actual lengths

- docs/incentive-mechanism/mining-reward.md
I noticed a grammatical error in the "Mining Reward" section.
The word "belongs" should be replaced with "belong" to match the plural subject "data chunks."  
The corrected sentence now reads:  
"...all the data chunks belong to this pricing segment..."  
This change ensures proper subject-verb agreement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/327)
> docs: fix grammatical error in "Mining Reward" section

- node/file_location_cache/src/file_location_cache.rs
- node/miner/src/pora.rs
Fixed typo: "annoucement" → "announcement" for correct spelling and consistency across test function names.
Fixed typo: "availiable" → "available" (correct spelling).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/344)
> Fixing Typos and Improving Code Consistency

- .github/workflows/abi.yml
- .github/workflows/cc.yml
- .github/workflows/rust.yml
- .github/workflows/tests.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/365)
> ci: bump actions/checkout to v4

- common/merkle_light/benches/ringx/init.rs
This PR replaces the deprecated `std::sync::ONCE_INIT` with `std::sync::Once::new()` to ensure compatibility with modern Rust versions (1.38+). The previous usage of `ONCE_INIT` generated deprecation warnings and could potentially break in future Rust updates.
Before Fix (Error)
After Fix (Successful Build)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/350)
> fix: Replace deprecated `ONCE_INIT` with `Once::new()` for Rust compatibility 
