common/append_merkle/src/lib.rs, common/append_merkle/src/merkle_tree.rs, common/append_merkle/src/proof.rs, node/chunk_pool/src/handler.rs, node/chunk_pool/src/mem_pool/chunk_cache.rs, node/chunk_pool/src/mem_pool/chunk_pool_inner.rs, node/log_entry_sync/src/sync_manager/mod.rs, node/rpc/src/zgs/impl.rs, node/shared_types/src/lib.rs, node/storage-async/src/lib.rs, node/storage/src/log_store/log_manager.rs, node/storage/src/log_store/mod.rs, node/sync/src/controllers/serial.rs, node/sync/src/service.rs, tests/test_all.py, tests/test_framework/bsc_node.py, tests/utility/simple_rpc_proxy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/9)
=> Update the merkle tree with proof data.

common/append_merkle/src/lib.rs, common/append_merkle/src/proof.rs, tests/config/node_config.py, tests/test_framework/blockchain_node.py
- Update contracts to latest compiled version
- Fix python tests, clippy issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/11)
=> fix: contract, tests, clippy

tests/test_framework/test_framework.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/16)
=> enhance test framework for extensibility

tests/test_framework/blockchain_node.py, tests/test_framework/test_framework.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/17)
=> hotfix for py test

tests/test_framework/test_framework.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/19)
=> enhance py test framework to support more args

node/chunk_pool/src/mem_pool/chunk_pool_inner.rs, node/rpc/src/config.rs, node/rpc/src/lib.rs, node/rpc/src/zgs/api.rs, node/rpc/src/zgs/impl.rs, node/src/client/builder.rs, node/src/config/convert.rs, node/src/config/mod.rs
- Add new rpc upload_segments to upload data batchly
- Add max_request_body_size to limit single rpc request size
- Fix minor issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/21)
=> feat: upload_segments

Cargo.lock, common/append_merkle/Cargo.toml, common/append_merkle/src/merkle_tree.rs, common/append_merkle/src/sha3.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-rust/24)
=> Cache zero hash results.

.gitmodules, common/contract-interface/build.rs, common/contract-interface/src/lib.rs, doc/install.md, doc/run.md, node/build.rs, tests/test_framework/test_framework.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/25)
=> @peter/update submodule

Cargo.toml, common/contract-interface/build.rs, node/storage/Cargo.toml, tests/test_framework/blockchain_node.py, tests/test_framework/bsc_node.py, tests/test_framework/conflux_node.py, tests/test_framework/contracts.py, tests/test_framework/test_framework.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/29)
=> Migrate to the new contract interfaces

.github/workflows/tests.yml, node/log_entry_sync/src/sync_manager/config.rs, node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs, node/log_entry_sync/src/sync_manager/log_query.rs, node/log_entry_sync/src/sync_manager/mod.rs, node/src/config/convert.rs, node/src/config/mod.rs, node/storage/src/lib.rs, node/storage/src/log_store/log_manager.rs, node/storage/src/log_store/mod.rs, node/storage/src/log_store/tx_store.rs, tests/random_test.py, version-meld/eth2_ssz/src/decode/impls.rs, version-meld/eth2_ssz/src/encode/impls.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/32)
=> replace filter with eth_getLogs

node/chunk_pool/src/mem_pool/chunk_pool_inner.rs, node/rpc/src/zgs/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/36)
=> set uploaded_seg_num in FileInfo for rpc

.github/workflows/tests.yml, node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs, node/log_entry_sync/src/sync_manager/mod.rs, node/src/config/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/37)
=> query getLogs from batch blocks

tests/config/evmos-init-genesis.sh, tests/config/node_config.py, tests/mine_test.py, tests/mine_with_market_test.py, tests/random_test.py, tests/revert_test.py, tests/test_framework/blockchain_node.py, tests/test_framework/evmos_node.py, tests/test_framework/test_framework.py, tests/test_framework/zgs_node.py, tests/utility/run_all.py, tests/utility/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/40)
=> Supports evmos as blockchain fullnode in python tests

run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/42)
=> update default config

tests/test_framework/evmos_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/43)
=> Supports custom flags to launch evmos node in python test

README.md, tests/test_framework/bsc_node.py, tests/test_framework/conflux_node.py, tests/test_framework/evmos_node.py, tests/test_framework/test_framework.py, tests/utility/build_binary.py, tests/utility/run_all.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/57)
=> Automatically install dependent blockchain binary when run a single python test

tests/test_framework/blockchain_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/59)
=> Enable data seal & merkle proof verification on mine

.github/workflows/tests.yml, tests/test_framework/evmos_node.py, tests/test_framework/test_framework.py, tests/utility/build_binary.py, tests/utility/run_all.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/61)
=> Supports to download blockchain binaries from github release

Cargo.lock, node/Cargo.toml, node/miner/src/config.rs, node/miner/src/lib.rs, node/miner/src/mine.rs, node/miner/src/pora.rs, node/miner/src/recall_range.rs, node/miner/src/submitter.rs, node/miner/src/watcher.rs, node/src/config/convert.rs, node/src/config/mod.rs, tests/mine_test.py, tests/mine_with_market_test.py, tests/test_framework/blockchain_node.py, tests/test_framework/contract_proxy.py, tests/utility/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/64)
=> Support mining on sharded storage. 

node/chunk_pool/src/handler.rs, node/rpc/src/zgs/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/73)
=> Enhance logs for rpc and chunk pool modules

node/src/config/convert.rs, node/src/config/mod.rs, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/84)
=> Supports discv5 related configurations

node/network/src/config.rs, node/src/config/convert.rs, node/src/config/mod.rs, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/86)
=> Add discv5 config and enlarge the default rate limiter

tests/test_framework/blockchain_node.py
- Update contract submodule
- Fix python tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/93)
=> feat: contract refactor

node/src/config/convert.rs, node/src/config/mod.rs, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/97)
=> enhance default config value

node/sync/src/controllers/serial.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/102)
=> Fix sync state machine issue for sharding case

node/router/src/libp2p_event_handler.rs, node/sync/src/lib.rs, node/sync/src/service.rs, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/103)
=> Enhance log level

scripts/update_config.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/106)
=> @peter/update config script

node/router/src/service.rs, node/sync/src/auto_sync/batcher_serial.rs, node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/109)
=> opt log level for file announcement relevant logs

Cargo.lock, node/Cargo.toml, node/router/Cargo.toml, node/router/src/libp2p_event_handler.rs, node/src/config/convert.rs, node/src/main.rs, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/115)
=> Use public ip address to broadcast file announcement

node/src/cli/mod.rs, node/src/config/mod.rs, run/config-testnet.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/116)
=> enhance config and cli

node/sync/src/controllers/peers.rs, node/sync/src/controllers/serial.rs
1. Added some helpful log to analyze file sync progress.
2. Change the max failures from 100 to 5.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/122)
=> Enhance sync logs

node/sync/src/auto_sync/batcher_random.rs, node/sync/src/auto_sync/batcher_serial.rs, node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/125)
=> disable auto sync until catched up

node/rpc/Cargo.toml, node/rpc/src/admin/api.rs, node/rpc/src/admin/impl.rs, node/rpc/src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/127)
=> Add admin RPC to dump discovered peers

node/rpc/src/admin/api.rs, node/rpc/src/admin/impl.rs, node/rpc/src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/128)
=> enhance admin rpc to return peers instead of dump

node/router/src/libp2p_event_handler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/130)
=> Verify announced IP with seen ip for pubsub msg

node/rpc/src/admin/api.rs, node/rpc/src/admin/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/138)
=> feat: add all_shards in admin_getFileLocation

node/sync/src/auto_sync/batcher.rs, node/sync/src/controllers/serial.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/136)
=> Terminate file sync if connecting peers too long

node/sync/src/auto_sync/batcher.rs, node/sync/src/auto_sync/batcher_random.rs, node/sync/src/auto_sync/batcher_serial.rs, node/sync/src/auto_sync/manager.rs, node/sync/src/auto_sync/mod.rs, node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/150)
=> Refactor auto sync to return sync status

node/rpc/src/admin/api.rs, node/rpc/src/admin/impl.rs, node/sync/src/lib.rs, node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/151)
=> Add admin rpc to return sync service state

node/src/log.rs
Fix the log_config error caused by the row trailing whitespace characters
> `: Invalid Filter Directive
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/146)
=> fix:log config : invalid filter directive

node/sync/src/auto_sync/batcher.rs, node/sync/src/auto_sync/batcher_random.rs, node/sync/src/auto_sync/batcher_serial.rs, node/sync/src/auto_sync/mod.rs, node/sync/src/controllers/mod.rs, node/sync/src/controllers/peers.rs, node/sync/src/controllers/serial.rs, node/sync/src/lib.rs, node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/153)
=> Change hardcoded const variables to configs in sync package

node/sync/src/auto_sync/batcher.rs, node/sync/src/auto_sync/batcher_random.rs, node/sync/src/lib.rs, run/config-testnet.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/154)
=> Supports batch randomly auto sync files

node/miner/src/config.rs, node/pruner/src/lib.rs, node/src/config/convert.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/157)
=> more robust provider

node/router/src/libp2p_event_handler.rs, node/sync/src/service.rs, run/log_config_debug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/160)
=> opt router debug logs

Cargo.lock, Cargo.toml, node/rpc/Cargo.toml, node/rpc/src/admin/api.rs, node/rpc/src/admin/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/162)
=> Add admin rpc to exports metrics

node/router/src/lib.rs, node/router/src/libp2p_event_handler.rs, node/router/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/163)
=> Do not verify announced ip address by default

Cargo.lock, common/channel/Cargo.toml, common/channel/src/channel.rs, common/channel/src/lib.rs, common/channel/src/metrics.rs, node/log_entry_sync/Cargo.toml, node/log_entry_sync/src/sync_manager/metrics.rs, node/log_entry_sync/src/sync_manager/mod.rs, node/router/src/libp2p_event_handler.rs, node/rpc/src/admin/impl.rs, node/sync/src/auto_sync/batcher.rs, node/sync/src/auto_sync/batcher_random.rs, node/sync/src/auto_sync/batcher_serial.rs, node/sync/src/auto_sync/metrics.rs, node/sync/src/controllers/metrics.rs, node/sync/src/controllers/mod.rs, node/sync/src/controllers/serial.rs, node/sync/src/lib.rs, node/sync/src/service.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/164)
=> Add more metrics for file sync

node/network/src/lib.rs, node/router/src/libp2p_event_handler.rs, node/router/src/metrics.rs, node/sync/src/controllers/serial.rs, node/sync/src/service.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/167)
=> add timestamp in p2p rpc request id for latency stat

node/pruner/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/168)
=> do not fail on prune error

node/sync/src/lib.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/169)
=> opt sync config and update config file

tests/config/node_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/171)
=> adjust sync timeout in py test

node/miner/src/mine.rs, node/miner/src/miner_id.rs, node/miner/src/pora.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/170)
=> Fix issue found in auditions

common/contract-interface/build.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/172)
=> Fix contract interface build cache

node/file_location_cache/src/file_location_cache.rs, node/file_location_cache/src/lib.rs, node/file_location_cache/src/test_util.rs, node/network/src/lib.rs, node/network/src/types/pubsub.rs, node/router/src/batcher.rs, node/router/src/lib.rs, node/router/src/libp2p_event_handler.rs, node/router/src/metrics.rs, node/router/src/service.rs, node/shared_types/src/lib.rs, node/src/config/convert.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
1. Add P2P protocol version in network identity.
2. Allow to publish multiple file announcements at a time, and each announcement contains multiple files.
3. Optimize default parameters for file location cache.
4. Optimize metrics for `router` and `sync` package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/173)
=> Enhance P2P network protocol to support batch messages for performance concern

node/router/src/libp2p_event_handler.rs, node/src/config/convert.rs, node/storage/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/174)
=> notify file announcement to sync layer only if shard config matches

run/config-testnet-standard.toml, run/config-testnet-turbo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/175)
=> update boot nodes

node/log_entry_sync/src/sync_manager/log_query.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/176)
=> check error messages

node/rpc/src/types.rs, node/rpc/src/zgs/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/178)
=> return network identity for status rpc

node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs, node/log_entry_sync/src/sync_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/177)
=> Query logs via LogQuery in watch loop

node/miner/src/mine.rs, tests/mine_test.py, tests/mine_with_market_test.py, tests/test_framework/blockchain_node.py, tests/test_framework/zg_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/184)
=> Update mine test process to avoid random bugs on low-performance devices

node/log_entry_sync/src/sync_manager/config.rs, node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs, node/log_entry_sync/src/sync_manager/mod.rs, node/src/config/convert.rs, node/src/config/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/183)
=> Add configuration which can force sync from start_block_number

node/miner/src/mine.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/186)
=> Fix recall range computation for sharding

tests/config/0gchain-init-genesis.sh, tests/test_all.py, tests/test_framework/test_framework.py, tests/utility/run_all.py, tests/utility/submission.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/181)
=> Change zg chain block time in python tests

Cargo.lock, node/storage/Cargo.toml, node/storage/src/log_store/flow_store.rs, node/storage/src/log_store/load_chunk/bitmap.rs, node/storage/src/log_store/load_chunk/chunk_data.rs, node/storage/src/log_store/load_chunk/mod.rs, node/storage/src/log_store/load_chunk/seal.rs, node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/185)
=> Output debug log with serde_json and fix debug root db key.

node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/188)
=> reset parent block hash when reset progress

tests/mine_test.py, tests/mine_with_market_test.py, tests/test_framework/blockchain_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/191)
=> Use 0gchain to test mine tests

node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/197)
=> Use iterator to return padding data.

node/sync/src/controllers/metrics.rs, node/sync/src/controllers/serial.rs, node/sync/src/lib.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/198)
=> Allow user to configure network bandwidth for file sync

node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs, node/log_entry_sync/src/sync_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/199)
=> Handle cases where sequence is not continuous during catch-up

node/rpc/src/types.rs, node/rpc/src/zgs/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/200)
=> Add log entry sync info in zgs_getStatus rpc

Cargo.lock, node/Cargo.toml, node/log_entry_sync/Cargo.toml, node/miner/src/mine.rs, node/miner/src/pora.rs, node/miner/src/recall_range.rs, node/miner/src/submitter.rs, node/miner/src/watcher.rs, node/network/Cargo.toml, node/network/src/lib.rs, node/storage/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/203)
=> Fix issues found in auditions

Cargo.lock, node/Cargo.toml, node/src/cli/mod.rs, node/src/config/config_macro.rs, node/storage/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/204)
=> Resolve dependency issue from atty

node/pruner/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/205)
=> do not fail on pruner first reward chunk revert error

node/log_entry_sync/src/sync_manager/mod.rs, node/storage/src/config.rs, tests/config/0gchain-init-genesis-mac.sh, tests/test_framework/zg_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/206)
=> fix: finalize file does not need to save

Cargo.lock, node/network/Cargo.toml, node/network/src/config.rs, node/network/src/peer_manager/peerdb.rs, node/network/src/service.rs, node/network/src/types/globals.rs, node/network/tests/pm_tests.rs, node/router/src/libp2p_event_handler.rs, node/src/config/convert.rs, node/src/config/mod.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/209)
=> Supports to configure network peer db values in toml or env

node/rpc/src/config.rs, node/rpc/src/lib.rs, node/src/config/convert.rs, node/src/config/mod.rs, node/src/main.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml, tests/test_framework/zgs_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/213)
=> Optimize rpc config

node/sync/src/lib.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/214)
=> reduce default sync threads

node/storage/src/log_store/load_chunk/chunk_data.rs, node/storage/src/log_store/load_chunk/mod.rs, node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/215)
=> Fix issue in reverting the last incomplete tx.

node/log_entry_sync/src/sync_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/220)
=> fix: finalize check on tx sync

node/log_entry_sync/src/sync_manager/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/221)
=> fix: end_segment_index

node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/222)
=> fix: do not finalize same-root tx with missing data.

Cargo.lock, node/log_entry_sync/src/sync_manager/mod.rs, node/router/src/libp2p_event_handler.rs, node/rpc/src/zgs/impl.rs, node/src/client/builder.rs, node/storage-async/src/lib.rs, node/storage/Cargo.toml, node/storage/benches/benchmark.rs, node/storage/src/log_store/flow_store.rs, node/storage/src/log_store/log_manager.rs, node/storage/src/log_store/mod.rs, node/storage/src/log_store/tests.rs, node/sync/src/controllers/serial.rs, node/sync/src/service.rs, node/sync/src/test_util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/219)
=> @peter/async padding

node/storage/src/log_store/flow_store.rs, node/storage/src/log_store/mod.rs, node/storage/src/log_store/seal_task_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/212)
=> Avoid appending to_seal_set if sealer is not enabled

node/network/src/behaviour/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/189)
=> Add TopicScoreParams for gossipsubs.

node/shared_types/src/lib.rs, node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/224)
=> fix: pad tx based on the on-chain contract result.

node/rpc/src/zgs/api.rs, node/rpc/src/zgs/impl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/226)
=> feat: tx_seq rpc

node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/228)
=> Fix the dead loop problem

node/src/client/builder.rs, node/src/config/convert.rs, node/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/231)
=> Support shard in case the miner and the pruner is not enabled

node/router/src/lib.rs, node/router/src/libp2p_event_handler.rs, node/src/config/convert.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/233)
=> Supports custom public ip to announce file

node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/235)
=> fix: error handling

node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/240)
=> stop recovery when sending via the channel fails

node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/244)
=> Optimizing recover perf by reducing sync progress events

Cargo.lock, Cargo.toml, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/245)
=> Fix metrics config deser

node/storage/src/log_store/flow_store.rs, node/storage/src/log_store/log_manager.rs, node/storage/src/log_store/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/251)
=> Remove unused data and codes.

node/network/src/behaviour/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/259)
=> Ban peer if failed to decode pubsub message

node/network/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/261)
=> Improve rate limit for UDP discovery

Cargo.lock, node/log_entry_sync/Cargo.toml, node/log_entry_sync/src/sync_manager/config.rs, node/log_entry_sync/src/sync_manager/log_entry_fetcher.rs, node/log_entry_sync/src/sync_manager/mod.rs, node/src/config/convert.rs, node/src/config/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/263)
=> add timeout for RPC connections

node/rpc/src/types.rs, node/rpc/src/zgs/impl.rs, node/storage/src/log_store/log_manager.rs, node/storage/src/log_store/mod.rs, node/storage/src/log_store/tx_store.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/266)
=> RPC return file pruned info

node/storage/src/log_store/metrics.rs, node/storage/src/log_store/tx_store.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/268)
=> track tx seq number time consumed

node/storage/src/log_store/load_chunk/chunk_data.rs, node/storage/src/log_store/load_chunk/mod.rs, node/storage/src/log_store/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/270)
=> chore: expose chunk data

node/log_entry_sync/src/sync_manager/log_query.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/273)
=> update chain rpc returned error msg

node/src/client/builder.rs, node/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/275)
=> Always init chunk pool

node/network/src/lib.rs, node/src/config/convert.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/277)
=> Fix protocol version issue

requirements.txt, tests/snapshot_test.py, tests/test_framework/blockchain_node.py, tests/test_framework/test_framework.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/276)
=> add snapshot test

node/storage/src/log_store/log_manager.rs, node/storage/src/log_store/tx_store.rs, tests/test_framework/contract_proxy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/281)
=> fix tx store

node/network/src/lib.rs
…nodes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/282)
=> Upgrade network protocol version to auto disconnect from old version nodes

node/network/src/lib.rs, node/network/src/peer_manager/config.rs, node/network/src/peer_manager/mod.rs, node/network/src/peer_manager/peerdb.rs, node/network/src/rpc/codec/ssz_snappy.rs, node/network/src/rpc/methods.rs, node/network/tests/rpc_tests.rs, node/router/src/libp2p_event_handler.rs, node/router/src/metrics.rs, node/router/src/service.rs, node/src/client/builder.rs, node/src/config/convert.rs, node/src/main.rs, node/sync/src/controllers/peers.rs, node/sync/src/controllers/serial.rs, node/sync/src/service.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml, tests/network_tcp_shard_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/285)
=> Add shard config in STATUS message and only dail to shard config matched peers

node/storage-async/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/280)
=> remove unnecessary backtrace

DockerfileStandard, DockerfileTurbo
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/241)
=> add docker support

.gitignore, run/zgs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/288)
=> Add script for dev test purpose

node/network/src/behaviour/mod.rs, node/network/src/config.rs, node/network/src/lib.rs, node/router/src/service.rs, node/src/config/convert.rs, node/sync/src/controllers/serial.rs, node/sync/src/lib.rs, node/sync/src/service.rs, run/config-testnet-standard.toml, run/config-testnet-turbo.toml, run/config.toml, tests/crash_test.py, tests/sync_auto_random_v2_test.py, tests/sync_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/295)
=> Sync file from neighbors by default

Cargo.lock, node/rpc/Cargo.toml, node/rpc/src/lib.rs, node/rpc/src/middleware.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/298)
=> Supports generic metrics for rpc

node/network/src/rpc/mod.rs, node/network/src/rpc/rate_limiter.rs, node/router/src/lib.rs, node/router/src/libp2p_event_handler.rs, node/router/src/rate_limit.rs, node/router/src/service.rs, node/src/client/builder.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/299)
=> Supports rate limit for pubsub message

run/log_config_debug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/304)
=> Adjust debug log config

node/miner/src/submitter.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/324)
=> add dynamic gas price adjustment when submitting pora

docs/introduction.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/309)
=> docs: Fix broken deployment documentation link

README.md, docs/introduction.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/311)
=> replaced broken links

Cargo.lock, common/contract-wrapper/Cargo.toml, common/contract-wrapper/src/lib.rs, node/Cargo.toml, node/miner/Cargo.toml, node/miner/src/config.rs, node/miner/src/miner_id.rs, node/miner/src/submitter.rs, node/src/config/convert.rs, node/src/config/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/330)
=> add gas auto adjustment

node/log_entry_sync/src/sync_manager/config.rs
`nubmer`  -  `number`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/331)
=> fix spelling issues config.rs

node/pruner/src/lib.rs, node/src/client/builder.rs, node/src/main.rs, node/storage/src/log_store/log_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/354)
=> fix shard config init

node/network/src/peer_manager/network_behaviour.rs, node/network/src/peer_manager/peerdb/client.rs
node/network/src/peer_manager/network_behaviour.rs
dialied - dialed
node/network/src/peer_manager/peerdb/client.rs
An Zgs - A Zgs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/343)
=> fix spelling error and correct minor error

Dockerfile, DockerfileTurbo, node/src/cli/mod.rs, run/config-testnet-turbo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/366)
=> update the dockerfile to build the node

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/338)
=> docs: added a link to social network X

node/network/src/rpc/rate_limiter.rs, node/router/src/libp2p_event_handler.rs
to be use used -  `deleted extra use`
broadcase - broadcast - `fix typo`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/358)
=> fix issues

common/append_merkle/src/proof.rs, tests/test_framework/blockchain_node.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/368)
=> @peter/align with source

.github/workflows/cc.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/380)
=> fix the grcov version

common/append_merkle/src/proof.rs
Optimizes memory usage in `RangeProof::validate()` by eliminating unnecessary copying of the first layer.
- Replaced `range_leaves.to_vec()` with direct slice operations
- Added proper handling for edge cases when no iterations occur
- Maintained identical validation logic and behavior
- Reduces memory allocations during range proof validation
- Resolves TODO comment about avoiding first layer copying
- No breaking changes, all tests pass
- ✅ All existing tests pass
- ✅ Clippy clean
- ✅ No regression in functionality
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-node/371)
=> perf(append_merkle): avoid copying first layer in range proof validation
